import type { HaClient } from "./client.js";
import type { Person, Roster } from "../people.js";

/**
 * The household roster, stored in Home Assistant itself ([ADR-0026]).
 *
 * **A person is an HA label; their calendar is the entity wearing it.**
 *
 * This replaces the `people.json` file. The file was operator config, which
 * meant SSH-ing to the server to add a child. Labels are editable from the app,
 * shared across every HA user and device, survive upgrades, need nothing in
 * this repo, and show up in HA's own UI where they can also be managed.
 *
 * Verified against HA 2026.7.2:
 *   - a label's `color` accepts an arbitrary hex string, not just HA's palette
 *   - `label_id` is **stable across a rename**, which is what [ADR-0021]
 *     requires of a person id -- it is what chore completions get logged
 *     against, so renaming "Emma" must not orphan her history
 *   - labels and entity-registry entries are both readable in one round trip
 */

/** Only labels attached to a calendar entity are people. */
export const CALENDAR_DOMAIN = "calendar.";
/** A person's chore list carries the same label as their calendar. */
export const TODO_DOMAIN = "todo.";

/**
 * The label that tells a person's two calendars apart ([ADR-0030]).
 *
 * A person now wears their label on *two* calendars: the one their events live
 * on, and the one their repeating chores are scheduled on. Nothing else can
 * separate them -- entity ids are renameable and `local_calendar` exposes no
 * kind or category -- so the schedule calendar carries a second, shared label
 * and the personal calendar is simply the one without it.
 *
 * Matched by **name**, not by id: `label_id` is generated by HA and a
 * household that already had a label of this name would push ours to
 * `chore_schedule_2`. The automation resolves it the same way, with
 * `label_id('Chore schedule')`.
 */
export const CHORE_SCHEDULE_LABEL = "Chore schedule";
/** Colour of the schedule label, so it reads as machinery in HA's own UI. */
const CHORE_SCHEDULE_COLOR = "grey";

interface LabelEntry {
  label_id: string;
  name: string;
  color: string | null;
  icon: string | null;
  description: string | null;
}

interface EntityEntry {
  entity_id: string;
  labels?: string[];
  name?: string | null;
  original_name?: string | null;
}

interface ConfigEntry {
  entry_id: string;
  domain: string;
  title: string;
}

const FALLBACK_COLOR = "#0b7285";

/**
 * Read the roster: every label that is attached to exactly one calendar entity.
 *
 * A label with no calendar is not a person -- it is just an HA label someone
 * made for their own purposes, and this app must not claim it.
 */
export async function fetchRoster(
  client: HaClient,
  weekStartsOn = 0,
): Promise<Roster> {
  const [labels, entities] = await Promise.all([
    client.callWS<LabelEntry[]>({ type: "config/label_registry/list" }),
    client.callWS<EntityEntry[]>({ type: "config/entity_registry/list" }),
  ]);

  const scheduleLabelId = findScheduleLabel(labels);

  const calendarByLabel = new Map<string, string>();
  const choreCalendarByLabel = new Map<string, string>();
  const choreListByLabel = new Map<string, string>();
  for (const entity of entities) {
    const isCalendar = entity.entity_id.indexOf(CALENDAR_DOMAIN) === 0;
    const isTodo = entity.entity_id.indexOf(TODO_DOMAIN) === 0;
    if (!isCalendar && !isTodo) continue;

    const entityLabels = entity.labels ?? [];
    // A calendar wearing the schedule label holds chore *rules*, not events
    // ([ADR-0030]). It must never be mistaken for the person's own calendar.
    const isSchedule =
      isCalendar &&
      scheduleLabelId !== null &&
      entityLabels.indexOf(scheduleLabelId) !== -1;

    for (const labelId of entityLabels) {
      if (labelId === scheduleLabelId) continue;
      // First match wins, so a label on two entities stays deterministic.
      const into = isCalendar
        ? isSchedule
          ? choreCalendarByLabel
          : calendarByLabel
        : choreListByLabel;
      if (!into.has(labelId)) into.set(labelId, entity.entity_id);
    }
  }

  const people: Person[] = [];
  for (const label of labels) {
    if (label.label_id === scheduleLabelId) continue;
    const calendar = calendarByLabel.get(label.label_id);
    if (!calendar) continue;
    const choreList = choreListByLabel.get(label.label_id);
    const choreCalendar = choreCalendarByLabel.get(label.label_id);
    people.push({
      id: label.label_id,
      name: label.name,
      color: label.color ?? FALLBACK_COLOR,
      calendar,
      // Absent for anyone added before chore lists existed, or if theirs was
      // deleted. The chores view offers to make one rather than breaking.
      ...(choreList ? { choreList } : {}),
      // Absent for anyone added before repeats existed. Made on demand the
      // first time somebody schedules one.
      ...(choreCalendar ? { choreCalendar } : {}),
    });
  }

  people.sort((a, b) => a.name.localeCompare(b.name));
  return { weekStartsOn, people };
}

/**
 * Add a person: create their label, create their calendar, link the two.
 *
 * The calendar is created through the config entry flow, which is the only
 * way `local_calendar` can be made -- it has no YAML form. That flow is REST,
 * not websocket, which is why `HaClient` carries `callApi`.
 *
 * Not transactional. If a later step fails, the earlier ones are undone so a
 * half-made person doesn't linger in HA's settings.
 */
export async function createPerson(
  client: HaClient,
  name: string,
  color: string,
): Promise<Person> {
  const trimmed = name.trim();
  if (!trimmed) throw new Error("Give this person a name.");

  const label = await client.callWS<LabelEntry>({
    type: "config/label_registry/create",
    name: trimmed,
    color,
  });

  const entryIds: string[] = [];
  try {
    const calendarEntry = await createEntry(client, "local_calendar", {
      calendar_name: trimmed,
      import: "create_empty",
    });
    entryIds.push(calendarEntry);
    const calendar = await findEntity(client, calendarEntry, CALENDAR_DOMAIN);
    await label_(client, calendar, label.label_id);

    // Everyone gets a chore list, adults included -- they appear in the
    // "who did this?" picker and can own chores like anyone else.
    const todoEntry = await createEntry(client, "local_todo", {
      todo_list_name: `${trimmed} chores`,
    });
    entryIds.push(todoEntry);
    const choreList = await findEntity(client, todoEntry, TODO_DOMAIN);
    await label_(client, choreList, label.label_id);

    return { id: label.label_id, name: trimmed, color, calendar, choreList };
  } catch (err) {
    // Roll back so a failed add doesn't leave debris behind.
    await client
      .callWS({
        type: "config/label_registry/delete",
        label_id: label.label_id,
      })
      .catch(() => undefined);
    for (const entryId of entryIds) {
      await client
        .callApi("DELETE", `config/config_entries/entry/${entryId}`)
        .catch(() => undefined);
    }
    throw err;
  }
}

/** Attach labels to an entity, replacing whatever it had. */
async function label_(
  client: HaClient,
  entityId: string,
  ...labelIds: string[]
): Promise<void> {
  await client.callWS({
    type: "config/entity_registry/update",
    entity_id: entityId,
    labels: labelIds,
  });
}

/** The id of the shared "Chore schedule" label, or null if nobody has one. */
function findScheduleLabel(labels: LabelEntry[]): string | null {
  const wanted = CHORE_SCHEDULE_LABEL.toLowerCase();
  for (const label of labels) {
    if (label.name.trim().toLowerCase() === wanted) return label.label_id;
  }
  return null;
}

/**
 * The "Chore schedule" label, made the first time anybody schedules a repeat.
 *
 * Created on demand rather than at install: a household with no repeating
 * chores should not find a label in their HA settings explaining nothing.
 */
async function ensureScheduleLabel(client: HaClient): Promise<string> {
  const labels = await client.callWS<LabelEntry[]>({
    type: "config/label_registry/list",
  });
  const existing = findScheduleLabel(labels);
  if (existing) return existing;

  const created = await client.callWS<LabelEntry>({
    type: "config/label_registry/create",
    name: CHORE_SCHEDULE_LABEL,
    color: CHORE_SCHEDULE_COLOR,
    icon: "mdi:calendar-sync",
    description:
      "Marks a calendar as somebody's repeating chores. Made by the family " +
      "calendar; the nightly automation reads it.",
  });
  return created.label_id;
}

/**
 * Give a person somewhere to keep repeating chores ([ADR-0030]).
 *
 * Made on demand, so nobody carries a third entity until they use it. The new
 * calendar wears **both** labels -- theirs, so it can be paired back to them,
 * and the shared schedule one, so it is never mistaken for their own calendar.
 */
export async function createChoreCalendar(
  client: HaClient,
  person: Person,
): Promise<string> {
  const scheduleLabel = await ensureScheduleLabel(client);
  const entryId = await createEntry(client, "local_calendar", {
    calendar_name: `${person.name} chores`,
    import: "create_empty",
  });
  try {
    const calendar = await findEntity(client, entryId, CALENDAR_DOMAIN);
    await label_(client, calendar, person.id, scheduleLabel);
    return calendar;
  } catch (err) {
    await client
      .callApi("DELETE", `config/config_entries/entry/${entryId}`)
      .catch(() => undefined);
    throw err;
  }
}

/**
 * Give an existing person a chore list. Used for people added before chore
 * lists existed, and when someone's list has been deleted out from under them.
 */
export async function createChoreList(
  client: HaClient,
  person: Person,
): Promise<string> {
  const entryId = await createEntry(client, "local_todo", {
    todo_list_name: `${person.name} chores`,
  });
  try {
    const choreList = await findEntity(client, entryId, TODO_DOMAIN);
    await label_(client, choreList, person.id);
    return choreList;
  } catch (err) {
    await client
      .callApi("DELETE", `config/config_entries/entry/${entryId}`)
      .catch(() => undefined);
    throw err;
  }
}

export async function updatePerson(
  client: HaClient,
  id: string,
  name: string,
  color: string,
): Promise<void> {
  const trimmed = name.trim();
  if (!trimmed) throw new Error("Give this person a name.");
  // Only the label changes. `label_id` is stable, so chore history survives a
  // rename -- which is the whole reason a person is a label and not a name.
  await client.callWS({
    type: "config/label_registry/update",
    label_id: id,
    name: trimmed,
    color,
  });
}

/**
 * Remove a person.
 *
 * `deleteCalendar` is opt-in and destructive: a `local_calendar` holds real
 * events, and deleting the config entry deletes them with it. The default
 * detaches the person and leaves their calendar in place, which is recoverable.
 */
export async function deletePerson(
  client: HaClient,
  person: Person,
  deleteCalendar = false,
): Promise<void> {
  for (const entityId of [
    person.calendar,
    person.choreList,
    person.choreCalendar,
  ]) {
    if (!entityId) continue;
    await client
      .callWS({
        type: "config/entity_registry/update",
        entity_id: entityId,
        labels: [],
      })
      .catch(() => undefined);
  }

  await client.callWS({
    type: "config/label_registry/delete",
    label_id: person.id,
  });

  if (!deleteCalendar) return;
  for (const entityId of [
    person.calendar,
    person.choreList,
    person.choreCalendar,
  ]) {
    if (!entityId) continue;
    const entryId = await findConfigEntryFor(client, entityId);
    if (entryId) {
      await client
        .callApi("DELETE", `config/config_entries/entry/${entryId}`)
        .catch(() => undefined);
    }
  }
}

/**
 * Drive a config entry flow to completion. Returns the new entry id.
 *
 * `local_calendar` and `local_todo` are both config-flow only and both
 * scriptable over REST, which is the only reason this app can provision
 * anything without sending someone into HA's settings.
 */
async function createEntry(
  client: HaClient,
  handler: string,
  answers: Record<string, unknown>,
): Promise<string> {
  const started = await client.callApi<{ flow_id: string; type: string }>(
    "POST",
    "config/config_entries/flow",
    { handler, show_advanced_options: false },
  );
  const finished = await client.callApi<{
    type: string;
    result?: { entry_id: string };
  }>("POST", `config/config_entries/flow/${started.flow_id}`, answers);

  if (finished.type !== "create_entry" || !finished.result) {
    throw new Error("Home Assistant would not create that.");
  }
  return finished.result.entry_id;
}

/**
 * The entity of a given domain belonging to a config entry.
 *
 * The entity appears a moment after the flow completes, so this retries
 * briefly rather than assuming it is registered by the time we look.
 */
async function findEntity(
  client: HaClient,
  entryId: string,
  domain: string,
): Promise<string> {
  for (let attempt = 0; attempt < 12; attempt++) {
    const entities = await client.callWS<
      Array<EntityEntry & { config_entry_id?: string | null }>
    >({ type: "config/entity_registry/list" });
    const match = entities.filter(
      (entity) =>
        entity.config_entry_id === entryId &&
        entity.entity_id.indexOf(domain) === 0,
    )[0];
    if (match) return match.entity_id;
    await new Promise((resolve) => setTimeout(resolve, 250));
  }
  throw new Error("It was created but never appeared.");
}

async function findConfigEntryFor(
  client: HaClient,
  entityId: string,
): Promise<string | null> {
  const entities = await client.callWS<
    Array<EntityEntry & { config_entry_id?: string | null }>
  >({ type: "config/entity_registry/list" });
  const match = entities.filter((e) => e.entity_id === entityId)[0];
  return match?.config_entry_id ?? null;
}

/** Calendars with no person attached -- offered when adopting an existing one. */
export async function fetchUnassignedCalendars(
  client: HaClient,
): Promise<Array<{ entityId: string; name: string }>> {
  const [entities, entries] = await Promise.all([
    client.callWS<Array<EntityEntry & { config_entry_id?: string | null }>>({
      type: "config/entity_registry/list",
    }),
    client
      .callWS<ConfigEntry[]>({ type: "config_entries/get" })
      .catch(() => [] as ConfigEntry[]),
  ]);
  const titleByEntry = new Map(entries.map((e) => [e.entry_id, e.title]));

  return entities
    .filter(
      (entity) =>
        entity.entity_id.indexOf(CALENDAR_DOMAIN) === 0 &&
        (entity.labels ?? []).length === 0,
    )
    .map((entity) => ({
      entityId: entity.entity_id,
      name:
        entity.name ??
        entity.original_name ??
        titleByEntry.get(entity.config_entry_id ?? "") ??
        entity.entity_id,
    }));
}
